### ISSUE TITLE
add .gitignore file

### ISSUE THREAD

**Issue by ripgamer** [ripgamer/c#5]

**Comment by bajibpathan** [comment]
@ripgamer, With regards to this task, do we need to any files inside .gitignore? I'd like to take-up this task in case if no one started working on it. Please share me the file(s) list that we need to add it to .gitignore (if any) and also assign this issue.

Thank you,

**Comment by ripgamer** [comment]
**You got the job...**
Right now You can only add `.vscode` folder in `.gitignore`
